src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name): void
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description): void
    {
        $this->description = $description;
    }

    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * @param mixed $created_at
     */
    public function setCreatedAt($created_at): void
    {
        $this->created_at = $created_at;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name')
        ->add('description')
        ->add('created_at', DateTimeType::class)
        ->add('submit', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(['data_class' => Article::class]);
    }
}

templates/article/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ form(form) }}
    <a href="{{ path('article_index') }}">Back to the list</a>
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<a href="{{ path('article_new') }}">Create article</a>
<table border="1">
    {% for article in articles %}
        <tr>
        <td>{{ article.id }}</td>
        <td>{{ article.name }}</td>
        <td>{{ article.description}}</td>
        <td>{{ article.createdAt|date('y\m\d') }}</td>
        <td><a href="{{ path('article_edit', {'id': article.id}) }}">update</a></td>
        <td><a href="{{ path('article_delete', {'id': article.id}) }}">delete</a></td>
        </tr>
    {% endfor %}
</table>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {#{{ form(edit_form) }}#}
    <a href="{{ path('article_index') }}">Back to the list</a>
{% endblock %}

templates/article/update.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {{ form(edit_form) }}
    <a href="{{ path('article_index') }}">Back to the list</a>
{% endblock %}